# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Publish Package to npmjs

on:
  push:
    branches:
      - master

# 权限配置
permissions:
  id-token: write # Required for OIDC
  contents: write # 允许仓库内容修改，用于创建 标签和版本
jobs:
  build-and-publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: master
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/

      - name: Update npm
        run: npm install -g npm@latest

      - run: npm i
      - run: npm run lib-build
      - run: |
          cd dist-lib
          npm run publish
      
      - name: Read version from package.json
        id: read_version
        run: |
          VERSION=$(jq -r .version dist-lib/package.json)
          echo "VERSION=${VERSION}" >> $GITHUB_OUTPUT

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.read_version.outputs.VERSION  }}
          release_name: Release v${{ steps.read_version.outputs.VERSION }}
          draft: false
          prerelease: false
